apiVersion: apps/v1
kind: Deployment
metadata:
  name: sports-nexus
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sports-nexus
  template:
    metadata:
      labels:
        app: sports-nexus
    spec:
      containers:
        - name: backend
          image: YOUR_ECR_IMAGE:latest
          ports:
            - containerPort: 8080
